aws/aws_kms.go, aws/aws_kms_test.go, secrets.go
AWS KMS cannot act as a secret store where we can store user data.
It provides a mechanism to generate DataKeys that could be used
for encrypting user data. In KMS when you generate a DataKey it returns
1. [Private Key]: PlainText which should be used for encrypting data.
2. [Public Key]: CipherText which should be used for subsequent calls to KMS to fetch the private key.
- Add two persistence stores for AWS KMS to store the public key
- filePersistenceStore - uses files on host
- kvdbPersistenceStore - uses a key value database using portworx/kvdb
- Add support for storing user data in a secret store
- AWS KMS in conjunction with kvdb can store user data.
- For every secretData to be stored, a new DataKey is generated in KMS.
- PutSecret -> Using the private key and AES+GCM algorithm, …
=> Revamp the AWS KMS implementation of the Secrets interface.

aws/aws_kms.go, aws/aws_kms_test.go
- Allow resetting of secret.
- When using kvdbPersistenceStore encode the cipherText before putting into kvdb and decode
it while getting it back from kvdb.
=> AWS KMS Changes

aws/aws_kms.go, ibm/README.md, ibm/ibm_key_protect.go, ibm/ibm_key_protect_test.go, pkg/ibm/README.md, pkg/ibm/api.go, pkg/ibm/config.go, pkg/ibm/logger.go, pkg/store/store.go, pkg/store/store_file.go, pkg/store/store_kvdb.go
The changes are divided into 3 commits
Commit 1:
The IBM implementation of the Secrets interface. 
Commit 2:
Adds a new pkg called IBM. This is a golang REST client for the Key Protect Service. This is a pkg provided by IBM and will move to vendor soon.
Commit 3:
Move the persistenceStore interface from AWS KMS to its own package so that IBM Key Protect implementation of Secrets can also use it.
=> Integrate with IBM Key Protect

aws/aws_kms.go, aws/aws_kms_test.go, dcos/dcos.go, dcos/dcos_integration_test.go, docker/docker.go, docker/docker_test.go, ibm/README.md, ibm/ibm_key_protect.go, ibm/ibm_key_protect_test.go, k8s/README.md, k8s/k8s.go, k8s/k8s_test.go, kvdb/kvdb.go, kvdb/kvdb_test.go, pkg/store/store.go, pkg/store/store_file.go, pkg/store/store_kvdb.go, secrets.go, test/secrets.go, vault/vault.go, vault/vault_integration_test.go
- For IBM KeyProtect, if the secretData is not provided in PutSecret then
use the WrapCreateDEK API which will create the passphrase.
- Fix the kvdband file persistence stores
Modify UTs for all providers 
- Add a UT for DeleteSecret for all the providers which support Delete
- Use assert for all the tests.
=> Add a new API DeleteSecret to all the secret providers.

ibm/ibm_key_protect.go, pkg/ibm/api.go
- The IBM SDK is returning CRK in the errors. Strip the CRK from such errors.
- In a few error conditions the SDK is returning an error with an empty message. Return the actual error message as well.
=> IBM: Do not show CRK in errors.

ibm/ibm_key_protect.go, ibm/ibm_key_protect_test.go, secrets.go
Add a new keycontext flag SecretReferenceKey to indicate in PutSecret that
a new secret does not need to be created but only a reference to the existing secret
with a new name needs to be added in the persistence store.
=> IBM: Add support to add references in persistence store to specific keys

azure/azure_kv.go, azure/azure_kv_helper.go, azure/azure_kv_test.go, secrets.go
This PR add support for azure key vault, operation supported currently now are - 
GetSecret - Get secret with id from Azure KV
PutSecret -  Put secret data into azure KV
DeleteSecret - Delete secret with ID from Azure KV
To test -
1. Export following environment variable
AZURE_TENANT_ID - Azure active directory tenant ID
AZURE_CLIENT_ID - Azure application ID
AZURE_CLIENT_SECRET - Azure application Secret
AZURE_VAULT_URL - Azure key vault endpoint URL
AZURE_ENVIORNMENT 
**Note:** Application should have acl permission set for given vault URL. Permission needed -
**secrets - set/get/delete**
2. Run go test -v ./azure
=> Azure Key vault support

gcloud/gcloud_kms.go
- We were printing the err object, which could contain a http header with errors.
Google SDK provides an .Error() function that provides a friendly string format for the error.
=> Google Cloud KMS: Parse the error before returning

aws/aws_kms.go, aws/aws_kms_test.go, aws/credentials/credentials.go
- If the PublicData key context is provided, then store only the cipher text
in kvdb.
- Update the UTs
=> AWS KMS: Update the AWS KMS implementation to use PublicData in key contexts

pkg/store/store.go, pkg/store/store_kvdb.go
- This is to ensure that we do not overwrite the public or custom data stored
in persistence store.
=> Use kvdb.Create instead of kvdb.Put in Store implementation of kvdb.

aws/aws_kms.go, azure/azure_kv.go, dcos/dcos.go, docker/docker.go, gcloud/gcloud_kms.go, ibm/ibm_key_protect.go, k8s/k8s.go, kvdb/kvdb.go, secrets.go, vault/vault.go
This will allow us to switch between `lsecrets.Instance().String()` here:
https://github.com/libopenstorage/openstorage/blob/master/pkg/auth/secrets/secrets.go#L64
Instead of passing the secretsType into NewAuth.
Signed-off-by: Grant Griffiths <grant@portworx.com>
=> Add secret types constants to secrets base package

vault/vault.go, vault/vault_test.go
- This will allow skipping the backend version check during Vault instance
creation, which means secrets library does not need permissions to read sys/mounts/*
=> Add VAULT_BACKEND argument to Vault.

vault/vault.go
To enable a custom mount path for authentication method used command:
```
$ vault auth enable -path=my-login userpass
````
So it's a bit confusing to use `auth/my-login` as a mount parameter for secrets.
Expect `VAULT_AUTH_MOUNT_PATH` parameter to be without the 'auth/' prefix. 
Signed-off-by: Serhii Aheienko <serhii.aheienko@gmail.com>
=> vault: update auth mount path parameter

vault/vault.go
The kv version check fails if backend path has no '/' suffix.
This change fixes it.
Signed-off-by: Serhii Aheienko <serhii.aheienko@gmail.com>
=> vault: fix kv backend version check

vault/vault.go
Vault client doesn't use namespaces when retrieve engine details to get a kv version. This change fixes it. 
Signed-off-by: Serhii Aheienko <serhii.aheienko@gmail.com>
=> vault: list mounts within a namespace

vaulttransit/vaulttransit.go
Signed-off-by: Serhii Aheienko <serhii.aheienko@gmail.com>
Vault namespace is set twice for the `ensureEncryptionKey` function and it fails as there is no permissions for the resulting namespace. Fix it with this change.
Closes #
=> vaulttransit: fix the new function

.github/workflows/canary-integration-test.yml, Makefile, secrets.go, tests/scripts/deploy-validate-vault.sh, vault/vault.go, vault/vault_ci_integration_test.go, vault/vault_test.go
This commit introduces a way to hard-delete all versioned key from a
Vault Secret Engine configured with version 2.
By default keys are soft-deleted, so the delete can be undone and any
version/revision of the key can be recovered.
However, there are scenarios where we want to remove everthing.
This commit expands the keyContext by adding `DestroySecret` which ones
set to any value will destroy the key. This effectively impplement this
API spec: https://www.vaultproject.io/api/secret/kv/kv-v2#delete-metadata-and-all-versions
Also, integration tests have been added to run through github actions.
I've notificed the existence of `vault/vault_ci_integration_test.go`
but I suspect it's used by another CI elsewhere so I didn't touch it.
I've tried to integrate with it at first, but couldn't …
=> vault: add support for complete key deletion in kv v2

aws/credentials/credentials.go
Adding IMDSv2 support. Removing custom metadata function in favor of
aws api available in the sdk.
More info: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html
IMDSv2 only nodes will not be able to respond to the previous metadata url. AWS SDK has the ability to try both v2 and v1.
Closes #
Testing: Ran px on a IMDSv2 only node.
=> PWX-17627: Adding IMDSv2 support

aws/aws_kms.go, aws/credentials/credentials.go
GetProvider() function could not scale well when we tried to scale px
to 400 nodes. GetProvider() function was limited by api rate limiting
on EC2 side. This improvement patch takes care of two main things:
1. Minimizes the amount of GetMetadata() calls that we need to make.
2. Have an exponential backoff when such a limit is seen. There is an
additional issue to handle here which relates to the type of error
that is returned. Client timing out and EC2Metadata error are two
other forms of rate limit being hit for EC2 apis. This has been
handled by adding them to the list of errors that will undergo
exponential backoff.
See description above
Closes #PWX-20521
This is …
=> PWX-20521: Scaling GetProvider()

.github/workflows/google-kms-integraion-test.yml, gcloud/gcloud_kms.go, gcloud/gcloud_kms_integration_test.go, gcloud/gcloud_kms_test.go
Signed-off-by: dahuang <dahuang@purestorage.com>
We were facing issue with message too long when encrypting data with google KMS. This PR adds the functionality to divide the incoming data into chunks and encrypt/decrypt them one by one.
PWX-19815
Testing notes:
tested locally with 2.9.1.3 cluster with `pxctl cred create` and `pxctl cred validate` with google kms and google credentials. 
all unit test + integration test passed locally
=> PWX-19815 Add fix for message too long problem in google kms

.github/workflows/canary-integration-test.yml, vault/utils/utils.go
Signed-off-by: dahuang <dahuang@purestorage.com>
When authentication failed, it would throw nil pointer panic causing PX to be stuck without knowing the exact error. This PR handles the error handling from auth failure. 
PWX-24735
tested with local px cluster
=> PWX-24735 Fix nil pointer issue when auth fails

.github/workflows/aws-scm-integration-test.yml, .github/workflows/canary-integration-test.yml
Github can't find matching runners for `18.04`, switching to latest ubuntu will avoid this.
=> Update job runner versions

.github/workflows/canary-integration-test.yml
The minikube setup is operating with versions which are incompatible with the vault helm chart (which isn't pinned, now requires `>=1.22`).
=> Update minikube setup versions

aws/credentials/credentials.go
we need to load web identity credentials from env and it's loaded automatically when new session is established. this commit uses it whenever it's there
**Which issue(s) this PR fixes**
JIRA: PWX-33300
testing note:
- used this change in mpxe-api to load from webidentity provider. In fact, it loads the ec2role credentials as well. But I don't want to change the behavior of current code, so i'm simply adding the check instead of removing the ec2role provider.
=> PWX-33300 Use loaded credentials from sess when available

vault/utils/utils.go, vault/vault.go, vault/vault_cooldowns_test.go
* double "permission denied" REST error will put vault client into 5 minutes cooldown for all REST calls
* can disable via `VAULT_COOLDOWN_PERIOD:disabled`
Turns out it is easy to overwhelm Hasicorp's Vault, and accidentally cause DDOS-attack
As a fix, we're adding `REST cooldown` for 5 minutes, to all Vault REST client calls
* it is triggered by hitting 2 consecutive "permission denied" errors  (i.e. `PUT<key>` ++ `RENEW<token>` both responded w/ "permission denied")
Closes # PWX-36873
=> PWX-36873: Add vault cooldowns
